### PR TITLE
Improve router typing

### PR DESCRIPTION
**Pull request by phBalance**
- Add typing for router method so that it can be type checked by applications that replace the default router.

### CODE REVIEW

**Comment by yysun** [comment]
It is a good idea to provide the type for the router function. What about export a type alias in apprun.d.ts?
``` typescript
export type IRoute = (url: string, ...args: any[]) => any;
```

**Comment by phBalance** [comment]
I'll do up a change for that. What do you think of IRouter as a type name or do you feel IRoute is more in line with the existing code?

**Comment by yysun** [comment]
Thanks for the reminder. I think _Route_ is better.

**Comment by phBalance** [comment]
Not sure if you saw the change I pushed last week to add the type. Was that what you had in mind?

**Comment by yysun** [comment]
Can you change IRouter to Router?

**Comment by phBalance** [comment]
Yes. Not sure why you're making a distinction between type and interface having the I prefix but it's a simple enough change.

**Pull request merged**
